# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3e1d719dbb496dfc04744305fd455c0ecf4b61c20f17136f6a215f2f20ec2f969b0866da40469bedc394bc66a68a8da8135f482c4c54c8493f88403524cfb9

test:
  secret_key_base: 35e1f21506804878f63eb6602e5c231a9aa16bd92927b27cd119ddcd2426917483ecc8f643f5bf30a59d962303cdc6533dc597107f775d6f8561afdbddf16353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
